"""
Produce a human-readable evidence file: for every bug, the model's patch next to the
real developer's patch, so the repair numbers can be checked by eye rather than taken
on trust.

Reads only what is already on disk -- no model calls, nothing re-run.

Usage:
    python make_evidence.py
    python make_evidence.py --results_dir results/pilot_full --out REPAIR_EVIDENCE.md

What this establishes and what it does not:
    ESTABLISHES  the patch text is real, which file(s) it touches, and how it compares
                 line by line with the fix the developer actually wrote.
    DOES NOT     establish that the patch fixes the bug. That needs SWE-bench's test
                 suite (Docker). Judging "looks equivalent" by eye is evidence, not proof.
"""
import argparse
import json
import os
import re

from datasets import load_dataset

FILE_RE = re.compile(r"^diff --git a/(\S+)", re.MULTILINE)


def norm(p):
    return (p or "").strip().replace("\\", "/").lstrip("./").lower()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results_dir", default="results/pilot_full")
    parser.add_argument("--out", default="REPAIR_EVIDENCE.md")
    parser.add_argument("--dataset", default="princeton-nlp/SWE-bench_Verified")
    args = parser.parse_args()

    ds = load_dataset(args.dataset, split="test")
    gold = {r["instance_id"]: r["patch"] for r in ds}

    bugs = sorted(
        d for d in os.listdir(args.results_dir)
        if os.path.isdir(os.path.join(args.results_dir, d))
    )

    lines = [
        "# Repair stage evidence",
        "",
        "Generated by `make_evidence.py` from saved pipeline outputs. For each bug: the",
        "patch our pipeline produced, and the patch the real developer wrote.",
        "",
        "**What this shows:** the patch text is real, which files it touches, and how it",
        "compares to the actual fix.",
        "",
        "**What this does NOT show:** whether the patch fixes the bug. That requires",
        "SWE-bench's test suite under Docker, which has not been run. Any judgement of",
        "\"semantically equivalent\" below is by inspection, not by test.",
        "",
        "Config: Qwen2.5-Coder-7B via Ollama, single greedy sample (temperature 0),",
        "`--related_level_separate_file` (stage 2), `--fine_grain_separate_file`",
        "(stage 3), `--context_window 25` (repair).",
        "",
        "---",
        "",
    ]

    applied = right_file = 0
    for bug in bugs:
        path = os.path.join(args.results_dir, bug, "repair", "output_0_processed.jsonl")
        patch = ""
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                patch = (json.loads(f.readline()).get("model_patch") or "").strip()

        gold_patch = (gold.get(bug) or "").strip()
        gold_files = {norm(m) for m in FILE_RE.findall(gold_patch)}
        pred_files = {norm(m) for m in FILE_RE.findall(patch)}

        lines.append(f"## {bug}")
        lines.append("")
        if not patch:
            lines.append("**Result:** no patch produced (empty).")
            lines.append("")
        else:
            applied += 1
            hit = bool(gold_files & pred_files)
            right_file += hit
            verdict = "touches a file the real fix also changed" if hit else \
                      "**touches NO file the real fix changed**"
            lines.append(f"**Result:** patch produced, {verdict}.")
            lines.append("")
            lines.append(f"- files changed by our patch: `{sorted(pred_files)}`")
            lines.append(f"- files changed by real fix : `{sorted(gold_files)}`")
            lines.append("")
            lines.append("### Our patch")
            lines.append("```diff")
            lines.append(patch)
            lines.append("```")
            lines.append("")

        lines.append("### Real developer patch (gold)")
        lines.append("```diff")
        lines.append(gold_patch if gold_patch else "(not found in dataset)")
        lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("")

    n = len(bugs)
    summary = [
        "## Summary",
        "",
        f"- bugs run: **{n}**",
        f"- patch applies: **{applied}/{n}** ({applied / n * 100:.1f} %)",
        f"- patch applies AND touches a gold-changed file: **{right_file}/{n}** "
        f"({right_file / n * 100:.1f} %)",
        "",
        "Correctness (does it actually fix the bug) is NOT established here.",
        "",
    ]
    lines[15:15] = summary  # insert after the header block

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {args.out}  ({applied}/{n} applied, {right_file}/{n} right file)")


if __name__ == "__main__":
    main()
