"""
Re-align a patch's hunk headers to where each hunk ACTUALLY applies in the buggy file.

Why this exists: `git apply` does not require a hunk's header line number to be exact. If
the hunk's context and removed lines match a few lines away, it applies there - "with an
offset". So a SWE-bench gold patch can apply cleanly to base_commit while its `@@ -N`
header points at the wrong lines.

Found on scikit-learn__scikit-learn-10908: the gold hunk's header says line 971, but the
code it changes (`def get_feature_names`) starts at line 994 of the file at base_commit -
an offset of 22. Every scorer that trusted the header mapped the ground truth to the wrong
function (`inverse_transform`), which scored a CORRECT stage-2 prediction as a miss.

Only the GOLD patch needs this. Model patches are generated by Agentless against the exact
file content it read at base_commit, so their headers are already correct.

realign_patch(patch, read) -> (patch_with_corrected_headers, [(file, header_start, actual_start)])
where read(path) returns the buggy file's source (or None). A hunk whose old-side lines
cannot be found anywhere is left unchanged and reported with actual_start None, so a
failure is visible rather than silent. When the lines match in more than one place, the
match NEAREST the header is used - the same rule git apply follows.
"""
import re

HUNK_RE = re.compile(r"^@@ -(\d+)((?:,\d+)?) \+(\d+)((?:,\d+)?) @@(.*)$")


def _old_side(body):
    """The lines a hunk expects to find in the ORIGINAL file: context + removed."""
    old = []
    for ln in body:
        if ln.startswith("\\"):
            continue                      # "\ No newline at end of file"
        if ln.startswith("+"):
            continue
        if ln.startswith("-") or ln.startswith(" "):
            old.append(ln[1:])
        elif ln == "":
            old.append("")                # blank context line whose leading space was stripped
    return old


def _find_start(file_lines, old, header_start):
    n = len(old)
    if n == 0:
        return header_start

    def matches(s):
        return s >= 1 and file_lines[s - 1:s - 1 + n] == old

    if matches(header_start):
        return header_start
    for d in range(1, len(file_lines) + 1):          # search outward: nearest match wins
        for s in (header_start + d, header_start - d):
            if matches(s):
                return s
    return None


def realign_patch(patch, read):
    lines = (patch or "").splitlines()
    out, report = [], []
    cur, in_hunks = None, False
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("diff --git"):
            cur, in_hunks = None, False
            out.append(ln)
            i += 1
            continue
        if not in_hunks and ln.startswith("--- a/"):
            cur = ln[6:].strip()
        m = HUNK_RE.match(ln)
        if not m:
            out.append(ln)
            i += 1
            continue

        in_hunks = True
        j = i + 1                                    # collect this hunk's body
        while j < len(lines) and not lines[j].startswith("@@") \
                and not lines[j].startswith("diff --git"):
            j += 1
        body = lines[i + 1:j]

        header_start = int(m.group(1))
        actual = header_start
        src = read(cur) if cur else None
        if src is not None:
            found = _find_start(src.splitlines(), _old_side(body), header_start)
            actual = found if found is not None else header_start
            report.append((cur, header_start, found))
        delta = actual - header_start
        new_start = int(m.group(3)) + delta
        out.append(f"@@ -{actual}{m.group(2)} +{new_start}{m.group(4)} @@{m.group(5)}")
        out.extend(body)
        i = j
    return "\n".join(out) + ("\n" if (patch or "").endswith("\n") else ""), report
